apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "{{ variables.appName }}"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "{{ variables.appName }}"
    spec:
      containers:
        - name: "{{ variables.appName }}"
          image: "{{ variables.registryUrl }}/{{ variables.imageName }}"
          ports:
          - containerPort: {{ inputs.containerPort }}