apiVersion: v1
kind: Service
metadata:
    name: "{{ variables.appName }}"
    labels:
        app: "{{ variables.appName }}"
spec:
    type: ClusterIP
    ports:
    - port: {{ inputs.containerPort }}
      targetPort: {{inputs.containerPort}}
      protocol: TCP
      name: http
    selector:
        app: "{{ variables.appName }}"